site_name: Tisp
repo_name: GitHub
repo_url: https://github.com/tisp-lang/tisp
edit_uri: edit/master/doc/docs
pages:
  - Home: index.md
  - Language Specification: language_specification.md
  - For Developers: for_developers.md
  - Program As Patch: program_as_patch.md
theme: readthedocs
theme_dir: theme
